<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


class FWException extends TException {
  static $_TSPEC;

  public $errCode = null;
  public $additionalInformation = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'errCode',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'additionalInformation',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['errCode'])) {
        $this->errCode = $vals['errCode'];
      }
      if (isset($vals['additionalInformation'])) {
        $this->additionalInformation = $vals['additionalInformation'];
      }
    }
  }

  public function getName() {
    return 'FWException';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->errCode);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->additionalInformation);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('FWException');
    if ($this->errCode !== null) {
      $xfer += $output->writeFieldBegin('errCode', TType::STRING, 1);
      $xfer += $output->writeString($this->errCode);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->additionalInformation !== null) {
      $xfer += $output->writeFieldBegin('additionalInformation', TType::STRING, 2);
      $xfer += $output->writeString($this->additionalInformation);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

?>
